#!/bin/bash

# Creating config directories
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"
# mkdir -p "$XDG_CONFIG_HOME"/nixpkgs
echo "Creating config directories"

# Install nix packages

# ln -sf "$PWD/config.nix" "$XDG_CONFIG_HOME"/nixpkgs/config.nix
# echo "Linking config.nix"

# Install Nix packages from config.nix
# nix-env -iA nixpkgs.myPackages
# echo "Installing Nix packages"

# Fedora packages
sudo dnf install neovim tmux

# Starship Installing
curl -sS https://starship.rs/install.sh | sh
# brew option
# brew install starship neovim tmux

# linking config
ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim
echo "Linking nvim"
ln -sf "$PWD/.zshrc" "$HOME"/.zshrc
echo "Linking .zshrc"
ln -sf "$PWD/.tmux.conf" "$HOME"/.tmux.conf
echo "Linking tmux"
